# Basic settings

# I define the destination as a hidden folder. The whole idea is to
# abstract the site  away, so under normal circumstances we do not
# need to see the site files. But, we want to be able to reach them.
# The default is _site, so it makes sense to name it '.site'
destination: .site

name: Marcel van der Boom

# Used in feed
author: Marcel van der Boom
email: marcel@hsdev.com
timezone: Europe/Amsterdam

# We generated absolute permalinks, this will become the default of
# jekyll v2.0 and up.
relative_permalinks: false

github: mrvdb
twitter: mrvdb

# If there is an .htaccess file, publish it
include:
  - .htaccess
exclude:
  - wordpress.xml

# Used in tag generation plugin, must be quoted
tag_title_prefix: "Posts tagged with:&nbsp;&ldquo;"
tag_title_suffix: "&rdquo;"

# Make sure the sitemap.xml URL's are always absolute
# FIXME: this conflicts with my plan for subdomains
url: http://mrblog.nl

# Future posting is just silly
future: false

# Enable pagination
paginate: 5

# Force permalink without categories for now
# This is needed to allow freedom in directory location, so
# the url wont change when I change location of _posts folder.
# In short: this variable determines what directories are created.
permalink: /:year/:month/:day/:title.html

# Use rdiscount for markdown processing
markdown: rdiscount

# Use UTF-8 everywhere, why isn't this the default by now
encoding: UTF-8
