# Basic settings

# gems that need to be installed:
#  - git
#  - ruby-embed
#  - org-ruby
#      \_ ruby-pants
#  - rdiscount
#
# I define the destination as a hidden folder. The whole idea is to
# abstract the site  away, so under normal circumstances we do not
# need to see the site files. But, we want to be able to reach them.
# The default is _site, so it makes sense to name it '.site'
destination: .site

name: Marcel van der Boom

# Used in feed
author: Marcel van der Boom
email: marcel@hsdev.com
timezone: Europe/Amsterdam

# We generated absolute permalinks, this will become the default of
# jekyll v2.0 and up.
relative_permalinks: false

github: mrvdb
twitter: mrvdb

# If there is an .htaccess file, publish it
include:
  - .htaccess
  - .well-known

exclude:
  - _data/wordpress.xml

# Used in tag generation plugin, must be quoted
tag_title_prefix: "Posts tagged with:&nbsp;&ldquo;"
tag_title_suffix: "&rdquo;"

# Make sure the sitemap.xml URL's are always absolute
# FIXME: this conflicts with my plan for subdomains
# TODO: for deployment this is machine local, can we split it into a separate file and git ignore it?
#url: http://mrblog.nl
#url: http://localhost:4000

# Future posting is just silly
future: false

# Enable pagination
paginate: 5

# Force permalink without categories for now
# This is needed to allow freedom in directory location, so
# the url wont change when I change location of _posts folder.
# In short: this variable determines what directories are created.
permalink: /:year/:month/:day/:title.html

# Use rdiscount for markdown processing
# Why was this again?
markdown: rdiscount
#lsi: true

# Use UTF-8 everywhere, why isn't this the default by now
encoding: UTF-8

# Setting for the home timeline in the sidebar
# (cfr. livetwitter from somewhere )
social:
  service : 'o.mrblog.nl'
  user: 'mrb'
  mode: 'home_timeline'
  limit: 8

# Configuration for linking to mediagoblin
gmg:
  instance: 'https://media.mrblog.nl'
  presets:
    default:
      attr:
        class: 'gmg-media'

# TODO: the dir should be determined automatically.
git:
  dir: '.'
  baseurl: 'https://github.com/mrvdb/mrblog/commit/'
  nrofcommits: 25
  dateformat: "%Y-%m-%d"


collections:
  emacs:
    output: true
    